name: ci-lite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Sync deps (if pyproject exists)
        run: |
          if [ -f pyproject.toml ]; then
            uv sync
          else
            echo "No pyproject.toml; skipping sync"
          fi

      - name: Import check
        run: uv run python -c "import lsl_harness; print('import ok')"

      - name: CLI help (module entry)
        run: uv run python -m lsl_harness.cli --help

      - name: Run tests
        run: uv run pytest

      - name: Capture synthetic stream measurement
        run: |
          set -euo pipefail

          RESULTS_DIR="results/ci_synthetic_run"
          rm -rf "${RESULTS_DIR}"
          mkdir -p "${RESULTS_DIR}"

          uv run synthetic-outlet >"${RESULTS_DIR}/outlet.log" 2>&1 &
          OUTLET_PID=$!

          cleanup() {
            if kill -0 "${OUTLET_PID}" 2>/dev/null; then
              kill "${OUTLET_PID}" || true
              wait "${OUTLET_PID}" || true
            fi
          }
          trap cleanup EXIT

          for _ in $(seq 1 15); do
            if grep -q "Now streaming data" "${RESULTS_DIR}/outlet.log" 2>/dev/null; then
              break
            fi
            sleep 1
          done

          uv run lsl-harness measure \
            --duration-seconds 5 \
            --output-directory "${RESULTS_DIR}" \
            --no-summary

          uv run lsl-harness report "${RESULTS_DIR}"

          cleanup

      - name: Upload synthetic artifacts
        uses: actions/upload-artifact@v4
        with:
          name: synthetic-measurement
          path: results/ci_synthetic_run
