name: ci-lite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Sync deps (if pyproject exists)
        run: |
          if [ -f pyproject.toml ]; then
            uv sync
          else
            echo "No pyproject.toml; skipping sync"
          fi

      - name: Import check
        run: uv run python -c "import lsl_harness; print('import ok')"

      - name: CLI help (module entry)
        run: uv run python -m lsl_harness.cli --help

      - name: Run tests
        run: uv run pytest
